### PR TITLE
Build and deploy html Doxygen documentation

### PR DESCRIPTION
**Pull request by m7913d**

### CODE REVIEW

**Review by doomlaur — DISMISSED** [review]
Perfect, thanks! :+1:

**Review by doomlaur — APPROVED** [review]
Approving again! :tada:

**Comment by doomlaur** [comment]
@m7913d Oh no, I think we now have once again the same situation that I solved a merge conflict, meaning that I'm the last maintainer that pushed something, so I need your review as well, but probably you can't review it since you're the author. Right? :sweat_smile:

**Comment by m7913d** [comment]
I rebased it myself to the master branch. Now you should be able to commit.

It may be useful to decide which "Update branch" method we will use to update short living branches to the master branch before merging the PR. Personally, my favorite would be rebasing as it results in a cleaner git history, but has the disadvantage of force pushing the branch. What do you think?

**Comment by doomlaur** [comment]
In bigger collaborative projects, I'm not that fond of rebasing and force pushing because you lose the information in Git about why a certain change was necessary - which, in a bigger project where multiple developers are working, is often necessary (especially if the code is not properly documented). However, I do agree that it makes the Git history cleaner, and due to the fact that we are only two maintainers at the moment (and even if we get more, we probably won't be many in the end), I also think that rebasing and force-pushing would be better **_for short-lived branches_** (that is, small features / bug fixes, that don't include multiple people working on them). I would definitely not recommend it for larger branches where multiple people are working on it, though :sweat_smile: So let's do rebase + force push for short-lived branches then :wink: 

By the way: GitHub still tells me: `New changes require approval from someone other than doomlaur because they were the last pusher.` And, of course, it still shows that I already approved it. So I think we'll need to disable the rule again for a short time.

This is also something we should agree on (at least until we get more maintainers): if merge conflicts appear and the PR has been initiated by either of us, the only person that should merge the code is the one that wrote the code, as we'll otherwise run into similar issues :sweat_smile:

**Comment by m7913d** [comment]
I definetely agree: only force pushing for short lived branches.

**Pull request merged**
