### PR TITLE
Fix issue #18

### PR DESCRIPTION
**Pull request by doomlaur**
Fixes issue #18.

### CODE REVIEW

**Comment by m7913d** [comment]
@doomlaur Seems good. Should we add a unit test?

**Comment by doomlaur** [comment]
I asked myself the same question and I would like to open a discussion about it.

On the one hand, the answer to your question should always be "yes, of course!". In an ideal world, we would have unit tests for every important use case. However, the ECMA-376 specification is very complex, and writing tests for every use case is pretty much impossible. Of course, this is a bad excuse, as we should nevertheless try our best and write tests anyway, as good and as much as we can. However, due to the nature of this library, we need to save files into our repository and load them in the tests, meaning that the more cases (and thus, files) we have, the more chaotic it gets (at least not without some strategy on how to organize them).

Personally, I see it like this: I would like to have tests covering as many use cases as possible, however, we have to think about the granularity (due to the complexity of the specification). This is the reason why I thought that maybe for this case (some XML attribute handled incorrectly), an additional unit test wouldn't be absolutely necessary - but, of course, I'm open for discussion :wink: 

We could do one of the following:
1. We could handle this situation as "very specific" and not provide a unit test for it - just as I did. This option is not so great, but on the other hand, doing the same for every XML attribute would be a whole lot of work in the future.
2. Integrate this situation into the existing file `19_defined_names.xlsx`, meaning that our existing unit test would already account for this situation. However, this is a one-size-fits-all solution, so if we apply the same strategy to other issues in the future, we cannot test every combination of XML attributes either.
3. Write an additional unit test to explicitly handle this specific situation. (In this case, however, we should probably apply the same strategy to further similar issues, so we have to think about how we should handle all the files that we're using for testing).

Sorry for debating something that should usually not be debated, but due to the complexity of the ECMA-376 specification, I think XLNT is a special case. Of course, the situation would also be different if we had more contributors and/or some financing that allows us to concentrate more on correctness and standard-compliance, but we are not there - yet, at least :wink:

**Comment by m7913d** [comment]
Personally, I'm in favor of writing a unit test for every issue we fix. I understand we cannot write a unit test for every part of the ECMA-376 specification, but writing a unit test for every fixed issue at least ensures we do not encounter the same issue again in the future and should be doable with our limited number of resources. The [contribution guideline](https://github.com/xlnt-community/xlnt/blob/master/CONTRIBUTING.md#pull-request-checklist) also requests to add a test for the fixed issue.

I'm not sure creating a chaotic set of test files is an issue. I would just create another test for every fixed issue and don't care much about the existing ones (as long as they do not fail). A lot of tests could also be written without an actual test file; e.g. (1) create new workbook, (2) set attribute, (3) check if attribute is set, (3) save to temp file, (4) read temp file and (5) check if attribute is set. This would limit the number of needed files (and total git size).

Option 2 & 3 are fine for me. I don't think we should worry too much about testing every possible combination of attributes, most of them are rather independent of each other. We just have to be careful that when we extend a test, we don't accidentally change the functionality originally tested. A disadvantage of editing xlsx (i.e. zip) files is that git is not able to show the differences well.

However, I also understand that this is a rather simple reading issue (which may justify writing no test at all), but the fact that this issue exists may indicate that it is not a trivial use case, and may be overlooked in case of (partial) rewrite / reorganization of the relevant code in the future.

The final word is yours.

**Comment by doomlaur** [comment]
Alright, I added a simple unit test for workbook-wide defined names :+1:

**Review by m7913d — APPROVED** [review]
Thanks!

Small remark: I don't think we currently do anything with a defined_name without localSheetId. So, just skipping a defined_name without a localSheetId would behave identically at the moment.

**Comment by doomlaur** [comment]
I think it would be a good idea to extend our support for `definedNames` anyway, in which case we must make sure that it conforms to the specification. I think our current solution / design should help us to easily extend it in the future. Otherwise skipping `definedNames` without a `localSheetId` might lead to further issues in case certain features are not covered by unit tests (of course, writing unit tests is always important, but it might happen that not enough unit tests have been written, thus not covering all cases).

However, the code skipping `definedNames` without an ID will need to be adapted as well, so either way, we'll need to change some existing code in the future.

I would personally let the code as it is, since I think the way it works now should cause the least amount of issues / surprises in the future. But let me know if you think otherwise :slightly_smiling_face:

**Comment by m7913d** [comment]
I'm fine with how it is written now, I just wanted to note that we currently do nothing when `localSheetId` is missing, but I agree using an optional `localSheetId` is the most future proof.

**Pull request merged**
