### PR TITLE
Fix compilation on latest gcc version (gcc 14)

### PR DESCRIPTION
**Pull request by m7913d**
Include correct files when using fixed integer types:
 - stdint.h: defines the types in the global namespace
 - cstdint: defines the types in the std namespace

Configured CircleCI to run tests using latest gcc and CMake too.

Only convert all warnings into errors if explicitly requested (e.g. for CI) using XLNT_ALL_WARNINGS_AS_ERRORS option. Generated warnings depend on compiler version. Always converting all warnings into errors may result in the end user experiencing an undesired failed built in case a different compiler version is used than those tested by CI.

Update to latest utf8cpp version (v4.0.5). Old version (v3.1) uses std::iterator which is deprecated in C++17.

Use custom built docker images for CI, to allow setting up environment once. Dynamic CircleCI configuration used to automatically built, deploy and use the new docker image when the Dockerfile is changed.

xlnt::constants::ns: gcc 13/14 generates incorrect dangling reference warning. See https://stackoverflow.com/questions/78759847/gcc-14-possibly-dangling-reference-to-a-temporary-warning-or-not-depending-on.

compound_document_*streambuf: initialise current_sector_ before passing it to current_sector_ (to avoid warnings)

Run CI for CMake version 3.2 as this is the minimal supported version, according to the documentation.
Note that CMake 3.2 does not support C++17.

### CODE REVIEW

**Review by doomlaur — COMMENTED** [review]
Thanks - it looks good! However, I don't really like the fact that we're modifying external libraries (in this case `utfcpp`). Out of curiosity, I looked into the code of the current `master` branch of `utf8cpp` for [checked.h](https://github.com/nemtrif/utfcpp/blob/master/source/utf8/checked.h#L288) and [unchecked.h](https://github.com/nemtrif/utfcpp/blob/master/source/utf8/unchecked.h#L233) and it seems that they fixed the issues themselves. Apparently, they have been fixed in [this commit](https://github.com/nemtrif/utfcpp/commit/2b1521b48bb37258822c2ccdf1bd5c26081b7a69) which is available since utfcpp 3.1.1, while it seems that we're still using exactly one version before that, namely 3.1.

I do understand that the changes are important, and I don't have anything against merging this pull request in order to fix the (potentially urgent) compilation errors, I think we should still upgrade utfcpp (preferably to the latest version, if possible).

@m7913d I would like to know your opinion, and afterwards I can gladly accept your PR :slightly_smiling_face:

**Comment by m7913d** [comment]
@doomlaur  I will have a look if I can update to a newer version of the utf8cpp library. Maybe I should try to include it as a submodule, like it is done for libstudxml?

**Comment by doomlaur** [comment]
@m7913d That's a good question. Personally, for my own projects, I follow the following strategy:
- If the project has stable releases, I prefer using stable versions, in which case I take a stable version (the latest, if possible) and include it directly into my projects, by either copying the files (for header-only libraries), or copying the include (header) files and binaries (for compiled libraries).
- If the project does NOT have stable releases, I prefer using a Git submodule, as it is very easy to simply update the repository to another commit.

On the other hand, you can always also point the Git submodule to a certain commit, e.g. to the same commit as a certain stable release.

So, in the end, I think it's less important if we do it one way or the other, as long as we have a proper update strategy for our dependencies (especially in the long run). What do you think would be better, in your opinion?

**Comment by doomlaur** [comment]
> Removed std::iterator usage as it is deprecated in C++17.

Talking about removing deprecated features: a lot of the functionality from `<codecvt>` has been deprecated in C++17 and removed in C++26. XLNT uses [`std::codecvt_utf8_utf16`](https://en.cppreference.com/w/cpp/locale/codecvt_utf8_utf16) for [Unicode-correct path conversions under Windows](https://github.com/xlnt-community/xlnt/blob/master/source/utils/path.cpp#L234). This is a piece of code we should definitely rewrite to make it compatible with newer C++ versions. You can find an alternative implementation in https://github.com/tfussell/xlnt/issues/709 (read my reply).

**Comment by m7913d** [comment]
I have a slight preference for including it as a submodule (especially as tfussell already used submodules for this repo), as it makes it clearer where exactly the code came from and avoids that someone (unintentionally) changes the copied external code in this library, instead of fixing the upstream and/or switching to a newer release.

Maybe I should try to update to the latest v4 release or at least the latest v3 release.

**Comment by doomlaur** [comment]
Yep, I fully agree with you - then let's just use a submodule for `utfcpp`. As far as I can see, I think it should be easy to update at least to the latest v3 version - however, if possible, I would prefer updating to the latest v4 version.

**Review by doomlaur — APPROVED** [review]
Perfect, looks good, thank you! :+1: :smiley:

**Review by doomlaur — APPROVED** [review]
Approving again :slightly_smiling_face:

**Pull request merged**
