### PR TITLE
Update build/install/link documentation

### PR DESCRIPTION
**Pull request by m7913d**

### CODE REVIEW

**Review by doomlaur — APPROVED** [review]
Looks very good, thanks! :+1:

By the way, just to be sure, I think we should take care of some small copyright details before releasing a new version of XLNT from xlnt-community: namely, I think we should go through all source files and write the following:
```
Copyright (c) 2014-2022 Thomas Fussell
Copyright (c) 2024 xlnt-community
```

I can gladly go over all files and do the change, if you are fine with that :wink: I could send a PR for it, probably tomorrow.

**Comment by m7913d** [comment]
If you would like to change it immediately in every file, I'm fine with it. We could also take the approach to just update the copyright notice of a file, if we actually change that file.

**Comment by doomlaur** [comment]
That would also be a possibility. I don't exactly know what it would be the best, legally :sweat_smile: However, at least for me, I think I would otherwise forget very often to change the copyright year (and probably also many of our contributors), and since this is a task that requires a very little amount of work, I think it would be the easiest to change everything at once (e.g. once per year, at the beginning of each year). This way, we cannot forget it :smile:

**Comment by m7913d** [comment]
Ok, feel free to create the PR.

**Pull request merged**
